//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2Games.DAL
{
    using S2Games.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class S2_AvaliacaoEntities : DbContext
    {
        public S2_AvaliacaoEntities()
            : base("name=S2_AvaliacaoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Emprestimo>().ToTable("Emprestimo");
            modelBuilder.Entity<Jogo>().ToTable("Jogo");
            modelBuilder.Entity<Usuario>().ToTable("Usuario");
        }
    
        public virtual DbSet<Emprestimo> Emprestimoes { get; set; }
        public virtual DbSet<Jogo> Jogoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
